name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/beatlegger/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{secrets.PCKG_PUBLISH}}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: Publish github
      run: dotnet nuget push Transmission.API.RPC/bin/Release/*.nupkg --skip-duplicate --no-symbols true
