name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      transmission:
        image: lscr.io/linuxserver/transmission:version-3.00-r5
        ports:
          - 9091:9091

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory "TestResults"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults
        if: ${{ always() }}